./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
./server >> 50mb_result.txt;
sleep 1;
