./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
./server >> 1mb_result.txt;
sleep 1;
